### ISSUE TITLE
Zabbix-frontend repo bug in CentOS 7

### ISSUE THREAD

**Issue by anutator** [robertdebock/ansible-role-zabbix_repository#2]
## Describe the bug
I downloaded your roles from Ansible Galaxy. The fist role **ansible-role-zabbix_repository** has such lines:

```yml
    - name: enable zabbix-frontend
      community.general.ini_file:
        path: /etc/yum.repos.d/zabbix.repo
        section: zabbix-frontend
        option: enabled
        value: "1"
        mode: "0644"
      when:
        - ansible_os_family in [ "RedHat", "Rocky" ]
        - ansible_distribution_major_version == "7"
```
After that I have empty enabled repo without baseurl and only one line "enabled=1":

```ini
[zabbix-frontend]
enabled = 1
```

## Output
Then I try to install zabbix-agent using your role zabbix_agent I get error:

`fatal: [preprod-db1]: FAILED! => {"changed": false, "msg": "Failure talking to yum: Cannot find a valid baseurl for repo: zabbix-frontend"}`

The second little issue or question.
Why do you use RPM-GPG-KEY-ZABBIX-A14FE591 key? Can i change it to RPM-GPG-KEY-ZABBIX?

```
RPM-GPG-KEY-ZABBIX                                 16-Aug-2016 10:46                1333
RPM-GPG-KEY-ZABBIX-79EA5ED4                        16-Aug-2016 10:46                1333
RPM-GPG-KEY-ZABBIX-A14FE591                        16-Aug-2016 10:46                1719
RPM-GPG-KEY-ZABBIX-A14FE591-EL5                    14-Nov-2016 18:47                 954
zabbix-official-repo.key                           13-Aug-2016 05:23                2938
```
